# -*- mode: ruby -*-
# vi: set ft=ruby :

# Main Vagrantfile for the cidemo - this bootstraps the creation of the cidemo
# virtual machine.

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "cidemo" do |cidemo|
    #Setup the VM virtualbox setting
    cidemo.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 4096,"--vram", 12, "--cpus", 2]
      v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    end

    cidemo.vm.box = "centos/7"
    cidemo.vm.hostname = "cidemo"
    
    #setup forword port for local host use
    #note: consider using private network instead so VM is accessible from
    #host machine.  https://www.vagrantup.com/docs/networking/private_network.html
    cidemo.vm.network "forwarded_port", guest: 8080, host: 18080
    cidemo.vm.network "forwarded_port", guest: 4444, host: 14444
    cidemo.vm.provision "shell", path: "cidemo/scripts/provision.sh"
  end
end
