#!/bin/bash
#
# Copyright 2016 - CANARIE Inc. All rights reserved
#
# Synopsis: init.d script to start and stop a production instance of
#           jenkins slave.
#
#           From http://www.tldp.org/HOWTO/HighQuality-Apps-HOWTO/boot.html
#
#
#
# Blob Hash: $Id$
#
# -------------------------------------------------------------------------------
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. The name of the author may not be used to endorse or promote products
# derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY CANARIE Inc. "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

. /etc/init.d/functions

[ -f /etc/sysconfig/hostnoded ] && . /etc/sysconfig/hostnoded


usage() {
	echo "usage: $NAME {start|stop|status} "
	echo "This script is used for managing the production jenkins slave instance."
	exit 1
}

start() {
		sudo -u vagrant bash -c '/home/vagrant/host_node/startslave.sh'
}

stop() {
	sudo -u vagrant bash -c '/home/vagrant/host_node/stopslave.sh'
}

status() {
	echo "Status"
}

case $1 in
	start)
		start
		;;
	stop)
	    	stop
	    	;;
	restart)
		stop
		start
		;;
	status)
		status
		;;
	*)
		usage
		;;
esac

exit 0
